### ISSUE TITLE
Support for .exr files

### ISSUE THREAD

**Issue by Sridhar701Pitt** [delhoume/vlivplugins#1]
Please add support to view .exr images

**Comment by delhoume** [comment]
Hi,

I have created  a sample EXR plugin.
It uses the tinyexr.h single header file and might not work for all input files.
It does not handle EXR advanced features, (such as tiles), you may want to extend the source code (or use another library).

It worked on some sample images I found.

Here is the plugin you can put in vliv/plugins folder
![image](https://user-images.githubusercontent.com/1763447/184113402-6e5c3df9-60e2-44fb-bb4c-be99bfe7a47f.png)

This plugin has a leak but I cannot get it to work without a crash...

[exr.zip](https://github.com/delhoume/vlivplugins/files/9309293/exr.zip)

**Comment by delhoume** [comment]
No crash nor leak ...
